name: Build and upload Zip TotalCross

on:
  schedule:
    - cron: "0 3 * * 1-5"
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    name: Build '${{ matrix.project }}' Docker container
    strategy:
      fail-fast: false
      matrix:
        project: [ linux-amd64, linux-arm32v7, linux-arm64 ]
        include:
        # includes a new variable of npm with a value of 2
        # for the matrix leg matching the os and version
        - project: linux-amd64
          arch: amd64
        - project: linux-arm32v7
          arch: arm/7
        - project: linux-arm64
          arch: arm64/8

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Checkout TotalCross/totalcross
      uses: actions/checkout@v2
      with:
        repository: TotalCross/totalcross
        ref: master

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3

    - name: Allow multiarch
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
     
    - name: Build container
      run: |
        ls
        cd ${{ matrix.project }} 
        docker build . --tag totalcross/${{ matrix.project }}

    - name: Build TotalCross/totalcross
      run: |
        mkdir -p ${{ matrix.project }}/build
        docker run -v ${{ matrix.project }}/build:/build -v TotalCrossVM/:/sources -t totalcross/${{ matrix.project }} bash -c "cmake /sources -G Ninja && ninja"