name: Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v6.1.1, v7.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version (name of the tag to be referenced)'
        required: true

jobs:
  docker:
    name: DockerHub tagging
    strategy:
      fail-fast: false
      matrix:
        project: [ linux-amd64, linux-arm32v7, linux-arm64 ]
    runs-on: ubuntu-20.04
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Pull latest container
      run: docker pull totalcross/${{ matrix.project }}:latest
    - name: Tag latest container with the same repo tag
      run: docker tag totalcross/${{ matrix.project }}:latest totalcross/${{ matrix.project }}:${{ github.event.release.tag_name }}
    - name: Push the new tag
      run: docker push totalcross/${{ matrix.project }}:${{ github.event.release.tag_name }}